// The morpheme registry. Every root, prefix and suffix that can be collected.
//
// id     — stable key, used by words.js and by the Codex
// type   — prefix | root | suffix
// gloss  — what it means, in words a 10-year-old uses
// origin — latin | greek | old english
// forms  — surface spellings this morpheme shows up as (allomorphs)
// lit    — literal etymology, shown on the Codex card. Optional.

export const MORPHEMES = {

  // ---------- PREFIXES ----------
  un:      { type:'prefix', gloss:'not, opposite of',      origin:'old english', forms:['un'] },
  re:      { type:'prefix', gloss:'again, back',           origin:'latin',       forms:['re'] },
  dis:     { type:'prefix', gloss:'not, apart',            origin:'latin',       forms:['dis','dif'] },
  mis:     { type:'prefix', gloss:'wrong, badly',          origin:'old english', forms:['mis'] },
  pre:     { type:'prefix', gloss:'before',                origin:'latin',       forms:['pre'] },
  post:    { type:'prefix', gloss:'after',                 origin:'latin',       forms:['post'] },
  sub:     { type:'prefix', gloss:'under, below',          origin:'latin',       forms:['sub','sup','suf'] },
  super:   { type:'prefix', gloss:'above, beyond',         origin:'latin',       forms:['super','sur'] },
  trans:   { type:'prefix', gloss:'across, through',       origin:'latin',       forms:['trans'] },
  inter:   { type:'prefix', gloss:'between, among',        origin:'latin',       forms:['inter'] },
  intra:   { type:'prefix', gloss:'inside',                origin:'latin',       forms:['intra'] },
  ex:      { type:'prefix', gloss:'out, out of',           origin:'latin',       forms:['ex','e','ef'] },
  in_not:  { type:'prefix', gloss:'not',                   origin:'latin',       forms:['in','im','il','ir'],
             lit:'The same prefix changes shape to match the next sound: im-possible, il-legal, ir-regular.' },
  in_into: { type:'prefix', gloss:'in, into',              origin:'latin',       forms:['in','im'] },
  con:     { type:'prefix', gloss:'with, together',        origin:'latin',       forms:['con','com','col','cor','co'] },
  de:      { type:'prefix', gloss:'down, away, undo',      origin:'latin',       forms:['de'] },
  pro:     { type:'prefix', gloss:'forward, in favor of',  origin:'latin',       forms:['pro'] },
  ad:      { type:'prefix', gloss:'to, toward',            origin:'latin',       forms:['ad','ac','af','ag','ap','at','as'] },
  ob:      { type:'prefix', gloss:'against, in the way',   origin:'latin',       forms:['ob','oc','op'] },
  circum:  { type:'prefix', gloss:'around',                origin:'latin',       forms:['circum'] },
  per:     { type:'prefix', gloss:'through, thoroughly',   origin:'latin',       forms:['per'] },
  anti:    { type:'prefix', gloss:'against',               origin:'greek',       forms:['anti','ant'] },
  auto:    { type:'prefix', gloss:'self',                  origin:'greek',       forms:['auto','aut'] },
  tele:    { type:'prefix', gloss:'far off, distant',      origin:'greek',       forms:['tele'] },
  micro:   { type:'prefix', gloss:'small',                 origin:'greek',       forms:['micro'] },
  macro:   { type:'prefix', gloss:'large',                 origin:'greek',       forms:['macro'] },
  mono:    { type:'prefix', gloss:'one, single',           origin:'greek',       forms:['mono','mon'] },
  bi:      { type:'prefix', gloss:'two',                   origin:'latin',       forms:['bi'] },
  tri:     { type:'prefix', gloss:'three',                 origin:'greek',       forms:['tri'] },
  poly:    { type:'prefix', gloss:'many',                  origin:'greek',       forms:['poly'] },
  syn:     { type:'prefix', gloss:'together, same time',   origin:'greek',       forms:['syn','sym','syl'] },
  hyper:   { type:'prefix', gloss:'over, too much',        origin:'greek',       forms:['hyper'] },
  hypo:    { type:'prefix', gloss:'under, too little',     origin:'greek',       forms:['hypo'] },
  semi:    { type:'prefix', gloss:'half, partly',          origin:'latin',       forms:['semi'] },

  contra:  { type:'prefix', gloss:'against, opposite',     origin:'latin',       forms:['contra'] },
  uni:     { type:'prefix', gloss:'one',                   origin:'latin',       forms:['uni'] },
  para:    { type:'prefix', gloss:'beside, alongside',     origin:'greek',       forms:['para'] },
  dia:     { type:'prefix', gloss:'across, through',       origin:'greek',       forms:['dia'] },
  homo:    { type:'prefix', gloss:'same',                  origin:'greek',       forms:['homo','hom'] },
  mega:    { type:'prefix', gloss:'huge',                  origin:'greek',       forms:['mega'] },
  peri:    { type:'prefix', gloss:'around',                origin:'greek',       forms:['peri'] },
  epi:     { type:'prefix', gloss:'on, upon',              origin:'greek',       forms:['epi'] },
  centi:   { type:'prefix', gloss:'hundred, hundredth',    origin:'latin',       forms:['centi'] },
  pseudo:  { type:'prefix', gloss:'fake, false',           origin:'greek',       forms:['pseudo'] },
  a_not:   { type:'prefix', gloss:'without, not',          origin:'greek',       forms:['a','an'],
             lit:'The Greek "not". It hides at the front of anonymous, apathy and anarchy.' },

  se:      { type:'prefix', gloss:'apart, aside',           origin:'latin',       forms:['se'] },
  multi:   { type:'prefix', gloss:'many',                   origin:'latin',       forms:['multi'] },
  non:     { type:'prefix', gloss:'not',                    origin:'latin',       forms:['non'] },
  over:    { type:'prefix', gloss:'too much, above',        origin:'old english', forms:['over'] },

  // ---------- ROOTS ----------
  spect:  { type:'root', gloss:'to look, to watch',   origin:'latin', forms:['spect','spec','spic'] },
  port:   { type:'root', gloss:'to carry',            origin:'latin', forms:['port'] },
  dict:   { type:'root', gloss:'to say, to speak',    origin:'latin', forms:['dict','dic'] },
  script: { type:'root', gloss:'to write',            origin:'latin', forms:['script','scrib','scrip'] },
  rupt:   { type:'root', gloss:'to break, to burst',  origin:'latin', forms:['rupt'] },
  struct: { type:'root', gloss:'to build',            origin:'latin', forms:['struct','stru'] },
  tract:  { type:'root', gloss:'to pull, to drag',    origin:'latin', forms:['tract','trac'] },
  ject:   { type:'root', gloss:'to throw',            origin:'latin', forms:['ject','jec'] },
  duct:   { type:'root', gloss:'to lead',             origin:'latin', forms:['duct','duc'] },
  mit:    { type:'root', gloss:'to send',             origin:'latin', forms:['mit','miss','mis'] },
  pos:    { type:'root', gloss:'to place, to put',    origin:'latin', forms:['pos','pon','pound'] },
  vert:   { type:'root', gloss:'to turn',             origin:'latin', forms:['vert','vers'] },
  voc:    { type:'root', gloss:'voice, to call',      origin:'latin', forms:['voc','vok'] },
  aud:    { type:'root', gloss:'to hear',             origin:'latin', forms:['aud','audi'] },
  vis:    { type:'root', gloss:'to see',              origin:'latin', forms:['vis','vid'] },
  cred:   { type:'root', gloss:'to believe, to trust',origin:'latin', forms:['cred'] },
  form:   { type:'root', gloss:'shape',               origin:'latin', forms:['form'] },
  gress:  { type:'root', gloss:'to step, to go',      origin:'latin', forms:['gress','grad'] },
  fact:   { type:'root', gloss:'to make, to do',      origin:'latin', forms:['fact','fect','fic','fy'] },
  tain:   { type:'root', gloss:'to hold',             origin:'latin', forms:['tain','ten','tin'] },
  cede:   { type:'root', gloss:'to go, to yield',     origin:'latin', forms:['cede','ceed','cess'] },
  flect:  { type:'root', gloss:'to bend',             origin:'latin', forms:['flect','flex'] },
  pel:    { type:'root', gloss:'to drive, to push',   origin:'latin', forms:['pel','puls'] },
  sist:   { type:'root', gloss:'to stand',            origin:'latin', forms:['sist','stat','sta'] },
  scend:  { type:'root', gloss:'to climb',            origin:'latin', forms:['scend','scent'] },
  sect:   { type:'root', gloss:'to cut',              origin:'latin', forms:['sect','sec'] },
  man:    { type:'root', gloss:'hand',                origin:'latin', forms:['man','manu'] },
  ped:    { type:'root', gloss:'foot',                origin:'latin', forms:['ped','pod'] },
  terr:   { type:'root', gloss:'earth, land',         origin:'latin', forms:['terr','terra'] },
  aqua:   { type:'root', gloss:'water',               origin:'latin', forms:['aqua','aque'] },
  luc:    { type:'root', gloss:'light',               origin:'latin', forms:['luc','lum','lus'] },
  mort:   { type:'root', gloss:'death',               origin:'latin', forms:['mort'] },
  viv:    { type:'root', gloss:'to live',             origin:'latin', forms:['viv','vit'] },
  sens:   { type:'root', gloss:'to feel',             origin:'latin', forms:['sens','sent'] },
  nov:    { type:'root', gloss:'new',                 origin:'latin', forms:['nov'] },
  magn:   { type:'root', gloss:'great, large',        origin:'latin', forms:['magn'] },
  fer:    { type:'root', gloss:'to carry, to bring',  origin:'latin', forms:['fer'] },
  cap:    { type:'root', gloss:'to take, to seize',   origin:'latin', forms:['cap','cept','ceive','cip'] },
  graph:  { type:'root', gloss:'to write, to draw',   origin:'greek', forms:['graph','gram'] },
  phon:   { type:'root', gloss:'sound, voice',        origin:'greek', forms:['phon','phone'] },
  scope:  { type:'root', gloss:'to look at, to view', origin:'greek', forms:['scope','scop'] },
  meter:  { type:'root', gloss:'to measure',          origin:'greek', forms:['meter','metr'] },
  bio:    { type:'root', gloss:'life',                origin:'greek', forms:['bio'] },
  geo:    { type:'root', gloss:'earth',               origin:'greek', forms:['geo'] },
  chron:  { type:'root', gloss:'time',                origin:'greek', forms:['chron'] },
  therm:  { type:'root', gloss:'heat',                origin:'greek', forms:['therm'] },
  photo:  { type:'root', gloss:'light',               origin:'greek', forms:['photo','phot'] },
  hydr:   { type:'root', gloss:'water',               origin:'greek', forms:['hydr','hydro'] },
  astro:  { type:'root', gloss:'star',                origin:'greek', forms:['astro','aster'] },
  psych:  { type:'root', gloss:'mind, soul',          origin:'greek', forms:['psych'] },
  path:   { type:'root', gloss:'feeling, suffering',  origin:'greek', forms:['path'] },
  cycl:   { type:'root', gloss:'circle, wheel',       origin:'greek', forms:['cycl'] },
  dem:    { type:'root', gloss:'people',              origin:'greek', forms:['dem','demo'] },
  crat:   { type:'root', gloss:'power, rule',         origin:'greek', forms:['crat','cracy'] },
  therap: { type:'root', gloss:'healing',             origin:'greek', forms:['therap'] },
  naut:   { type:'root', gloss:'sailor',              origin:'greek', forms:['naut'] },
  arch:   { type:'root', gloss:'chief, ruler',        origin:'greek', forms:['arch'] },

  thes:   { type:'root', gloss:'to place, to put',     origin:'greek', forms:['thes','thesis'] },
  electr: { type:'root', gloss:'electricity',         origin:'greek', forms:['electr'],
            lit:'From the Greek word for amber. Rub amber on wool and it crackles.' },
  nom:    { type:'root', gloss:'law, order',          origin:'greek', forms:['nom','nomy'] },
  nym:    { type:'root', gloss:'name',                origin:'greek', forms:['nym','onym'] },
  soci:   { type:'root', gloss:'friend, companion',   origin:'latin', forms:['soci'] },
  act:    { type:'root', gloss:'to do, to drive',     origin:'latin', forms:['act','ig'] },
  gon:    { type:'root', gloss:'angle, corner',       origin:'greek', forms:['gon'] },

  fort:   { type:'root', gloss:'strong',              origin:'latin', forms:['fort'] },
  hend:   { type:'root', gloss:'to grasp, to seize',  origin:'latin', forms:['hend','hens'] },


  vent:   { type:'root', gloss:'to come',              origin:'latin', forms:['vent'] },
  mot:    { type:'root', gloss:'to move',              origin:'latin', forms:['mot','mote','mob'] },
  lect:   { type:'root', gloss:'to choose, to gather', origin:'latin', forms:['lect'] },
  fin:    { type:'root', gloss:'end, limit',           origin:'latin', forms:['fin','fine'] },
  son:    { type:'root', gloss:'sound',                origin:'latin', forms:['son'] },
  sci:    { type:'root', gloss:'to know',              origin:'latin', forms:['sci'] },
  spir:   { type:'root', gloss:'to breathe',           origin:'latin', forms:['spir','spire','pire'],
            lit:'Inspire, expire, respiration — every one of them is really about breathing.' },
  pend:   { type:'root', gloss:'to hang, to weigh',    origin:'latin', forms:['pend','pens'] },
  sign:   { type:'root', gloss:'mark, sign',           origin:'latin', forms:['sign'] },
  cur:    { type:'root', gloss:'to run',               origin:'latin', forms:['cur','curr','curs'] },
  plic:   { type:'root', gloss:'to fold',              origin:'latin', forms:['plic','ple','ply'] },
  press:  { type:'root', gloss:'to press',             origin:'latin', forms:['press'] },
  dent:   { type:'root', gloss:'tooth',                origin:'latin', forms:['dent'] },
  the:    { type:'root', gloss:'god',                  origin:'greek', forms:['the'] },
  nav:    { type:'root', gloss:'ship',                 origin:'latin', forms:['nav'] },

  // ---------- EVERYDAY BASES (Germanic) ----------
  // Low-friction warm-up stems. They also give the high-frequency English
  // suffixes something to attach to, which Latin roots alone do not.
  help:   { type:'root', gloss:'to help',        origin:'old english', forms:['help'] },
  care:   { type:'root', gloss:'to care',        origin:'old english', forms:['care'] },
  harm:   { type:'root', gloss:'hurt, damage',   origin:'old english', forms:['harm'] },
  use:    { type:'root', gloss:'to use',         origin:'old english', forms:['use'] },
  thought:{ type:'root', gloss:'thinking',       origin:'old english', forms:['thought'] },
  hope:   { type:'root', gloss:'to hope',        origin:'old english', forms:['hope'] },
  fear:   { type:'root', gloss:'to be afraid',   origin:'old english', forms:['fear'] },
  power:  { type:'root', gloss:'strength',       origin:'old english', forms:['power'] },
  kind:   { type:'root', gloss:'kind, friendly', origin:'old english', forms:['kind'] },
  dark:   { type:'root', gloss:'dark',           origin:'old english', forms:['dark'] },
  sad:    { type:'root', gloss:'sad',            origin:'old english', forms:['sad'] },
  friend: { type:'root', gloss:'friend',         origin:'old english', forms:['friend'] },
  rest:   { type:'root', gloss:'rest',           origin:'old english', forms:['rest'] },
  end:    { type:'root', gloss:'end',            origin:'old english', forms:['end'] },

  place:  { type:'root', gloss:'place',          origin:'old english', forms:['place'] },
  judge:  { type:'root', gloss:'to judge',       origin:'old english', forms:['judge'] },
  count:  { type:'root', gloss:'to count',       origin:'old english', forms:['count'] },
  spell:  { type:'root', gloss:'to spell',       origin:'old english', forms:['spell'] },
  trust:  { type:'root', gloss:'to trust',       origin:'old english', forms:['trust'] },
  read:   { type:'root', gloss:'to read',        origin:'old english', forms:['read'] },
  treat:  { type:'root', gloss:'to treat',       origin:'old english', forms:['treat'] },
  print:  { type:'root', gloss:'to print',       origin:'old english', forms:['print'] },
  view:   { type:'root', gloss:'to look at',     origin:'old english', forms:['view'] },
  real:   { type:'root', gloss:'real, actual',   origin:'old english', forms:['real'] },
  work:   { type:'root', gloss:'to work',        origin:'old english', forms:['work'] },
  play:   { type:'root', gloss:'to play',        origin:'old english', forms:['play'] },
  agree:  { type:'root', gloss:'to agree',       origin:'old english', forms:['agree'] },
  name:   { type:'root', gloss:'name',           origin:'old english', forms:['name'] },
  joy:    { type:'root', gloss:'joy',            origin:'old english', forms:['joy'] },
  wonder: { type:'root', gloss:'wonder',         origin:'old english', forms:['wonder'] },
  doubt:  { type:'root', gloss:'doubt',          origin:'old english', forms:['doubt'] },
  cover:  { type:'root', gloss:'to cover',       origin:'old english', forms:['cover'] },
  part:   { type:'root', gloss:'part, piece',    origin:'latin',       forms:['part'] },

  // ---------- SUFFIXES ----------
  tion:   { type:'suffix', gloss:'the act or result of',    origin:'latin', forms:['tion','sion','ation','ition'] },
  able:   { type:'suffix', gloss:'able to be',              origin:'latin', forms:['able','ible','ile'] },
  ment:   { type:'suffix', gloss:'the result of',           origin:'latin', forms:['ment'] },
  ness:   { type:'suffix', gloss:'the state of being',      origin:'old english', forms:['ness'] },
  ful:    { type:'suffix', gloss:'full of',                 origin:'old english', forms:['ful'] },
  less:   { type:'suffix', gloss:'without',                 origin:'old english', forms:['less'] },
  ly:     { type:'suffix', gloss:'in that way',             origin:'old english', forms:['ly'] },
  er:     { type:'suffix', gloss:'one who does it',         origin:'old english', forms:['er','or','ar'] },
  ist:    { type:'suffix', gloss:'one who does it',         origin:'greek', forms:['ist'] },
  ive:    { type:'suffix', gloss:'tending to',              origin:'latin', forms:['ive','ative','itive'] },
  al:     { type:'suffix', gloss:'relating to',             origin:'latin', forms:['al','ial'] },
  ic:     { type:'suffix', gloss:'relating to',             origin:'greek', forms:['ic','ical'] },
  ous:    { type:'suffix', gloss:'full of, having',         origin:'latin', forms:['ous','ious','eous'] },
  ity:    { type:'suffix', gloss:'the quality of',          origin:'latin', forms:['ity','ty'] },
  ize:    { type:'suffix', gloss:'to make into',            origin:'greek', forms:['ize','ise'] },
  ify:    { type:'suffix', gloss:'to make',                 origin:'latin', forms:['ify','fy'] },
  ance:   { type:'suffix', gloss:'the state of',            origin:'latin', forms:['ance','ence'] },
  ant:    { type:'suffix', gloss:'one who, doing',          origin:'latin', forms:['ant','ent'] },
  ary:    { type:'suffix', gloss:'relating to, place for',  origin:'latin', forms:['ary','ory','ery'] },
  logy:   { type:'suffix', gloss:'the study of',            origin:'greek', forms:['logy','ology'] },
  phobia: { type:'suffix', gloss:'fear of',                 origin:'greek', forms:['phobia','phobic'] },
  ate:    { type:'suffix', gloss:'to make, to become',       origin:'latin', forms:['ate'] },
  ism:    { type:'suffix', gloss:'a belief or practice',     origin:'greek', forms:['ism'] },
  ure:    { type:'suffix', gloss:'the act or result of',    origin:'latin', forms:['ure','ature'] },
  y:      { type:'suffix', gloss:'the state or study of',   origin:'greek', forms:['y'] },
  oid:    { type:'suffix', gloss:'shaped like',             origin:'greek', forms:['oid'] },
};

export const ORIGIN_LABEL = {
  latin: 'Latin',
  greek: 'Greek',
  'old english': 'Old English',
};
